import { ArtStyle, PlanType, AspectRatio, Language } from './types';
import { Palette, Camera, Smile, Square, Smartphone, Monitor, Star } from 'lucide-react';
import React from 'react';

export const STYLE_DETAILS = {
  [ArtStyle.NONE]: {
    icon: Square,
    promptSuffix: '',
  },
  [ArtStyle.ANIME]: {
    icon: Star,
    promptSuffix: ', anime style, clean line art, vibrant colors, soft lighting, expressive eyes',
  },
  [ArtStyle.CARICATURE]: {
    icon: Smile,
    promptSuffix: ', style of a caricature, exaggerated features, expressive proportions, artistic distortion',
  },
  [ArtStyle.REALISTIC]: {
    icon: Camera,
    promptSuffix: ', photorealistic, 8k, highly detailed, natural lighting, realistic textures',
  },
  [ArtStyle.CARTOON]: {
    icon: Palette,
    promptSuffix: ', cartoon style, simplified shapes, bold outlines, soft shading, friendly',
  },
};

export const PLAN_DETAILS = {
  [PlanType.BASIC]: {
    name: 'Basic',
    dailyTokens: 50,
    costPerImage: 10,
    resolution: 'Standard (768px)',
    description: 'Perfect for quick ideas and drafts.',
    model: 'Turbo/Magic',
  },
  [PlanType.PLUS]: {
    name: 'Plus',
    dailyTokens: 'Unlimited',
    costPerImage: 0,
    resolution: 'High Quality (1024px)',
    description: 'Professional quality with Flux model.',
    model: 'Flux/Turbo',
  },
};

export const ASPECT_RATIOS = [
  { value: AspectRatio.SQUARE, icon: Square },
  { value: AspectRatio.PORTRAIT, icon: Smartphone },
  { value: AspectRatio.LANDSCAPE, icon: Monitor },
  { value: AspectRatio.WIDE, icon: Monitor },
  { value: AspectRatio.TALL, icon: Smartphone },
];

export const TRANSLATIONS = {
  en: {
    appTitle: "Artify",
    createArt: "Create new art",
    desc: "Transform your text into unique artworks using",
    promptPlaceholder: "Describe your imagination... (e.g., A futuristic cyberpunk city at night with neon lights)",
    styleLabel: "Art Style",
    ratioLabel: "Aspect Ratio",
    generate: "Generate Art",
    generating: "Creating Masterpiece...",
    generatingShort: "Creating...",
    changeImage: "Change Image",
    addReference: "Add Reference",
    download: "Download",
    share: "Share",
    readyToCreate: "Ready to Create",
    readyDesc: "Select a style, enter a prompt, and watch Artify bring your ideas to life.",
    loadingDesc: "Analyzing your pixels…",
    insufficientTokens: "Insufficient tokens. Upgrade to Plus or wait for refill.",
    tokens: "Tokens",
    basicPlan: "Basic",
    plusPlan: "Plus",
    generatedWith: "Generated with Artify",
    currentPlan: "Current Plan",
    resolution: "Resolution",
    model: "Model",
    unlimited: "Unlimited",
    day: "day",
    back: "Back",
    editImage: "Edit Image",
    // Selection Screen
    photoEditor: "Photo Editor",
    photoEditorDesc: "Edit and enhance your photos like a pro.",
    aiGenerator: "Generate Images with AI",
    aiGeneratorDesc: "Turn text into stunning images.",
    tools: "Tools",
    toolsDesc: "Useful utilities for creators and designers.",
    unitConverter: "Unit Converter",
    unitConverterDesc: "Convert universal units instantly.",
    colorAnalyzer: "Color Analyzer",
    colorAnalyzerDesc: "Analyze colors from camera or images.",
    currencyConverter: "Currency Converter",
    currencyConverterDesc: "Real-time exchange rates.",
    comingSoon: "Coming Soon!",
    editorComingSoon: "The photo editor is currently under development.",
    // Mode Selection
    selectModeTitle: "Choose Editor Mode",
    selectModeDesc: "Select how you want to create your masterpiece",
    modeManual: "Manual Editor",
    modeManualDesc: "Classic professional tools. Adjust, crop, filter, and draw with precision control.",
    modeAI: "Edit with AI",
    modeAIDesc: "Enhance images, remove backgrounds, and add AI-generated objects instantly.",
    aiModeBadge: "AI MODE",
    // Styles
    [ArtStyle.NONE]: "No Style",
    [ArtStyle.ANIME]: "Anime",
    [ArtStyle.CARICATURE]: "Caricature",
    [ArtStyle.REALISTIC]: "Realistic",
    [ArtStyle.CARTOON]: "Cartoon",
    // Ratios
    [AspectRatio.SQUARE]: "Square (1:1)",
    [AspectRatio.PORTRAIT]: "Portrait (3:4)",
    [AspectRatio.LANDSCAPE]: "Landscape (4:3)",
    [AspectRatio.WIDE]: "Wide (16:9)",
    [AspectRatio.TALL]: "Stories (9:16)",
    // Editor
    editorUpload: "Upload Photo to Edit",
    editorDragDrop: "or drag and drop",
    editorTools: "Tools",
    editorAdjust: "Adjust",
    editorFilters: "Filters",
    editorCrop: "Crop",
    editorDraw: "Draw",
    editorText: "Text",
    editorSticker: "Stickers",
    editorLayers: "Layers",
    editorImport: "Add Image",
    editorSave: "Save",
    editorCancel: "Cancel",
    editorUndo: "Undo",
    editorRedo: "Redo",
    editorBrightness: "Brightness",
    editorContrast: "Contrast",
    editorSaturation: "Saturation",
    editorBlur: "Blur",
    editorHue: "Hue",
    editorRotate: "Rotate",
    editorFlipH: "Flip H",
    editorFlipV: "Flip V",
    editorBrushSize: "Size",
    editorColor: "Color",
    editorAddText: "Add Text",
    editorTextPlaceholder: "Type text...",
    editorCropOriginal: "Original",
    editorCropSquare: "Square",
    editorCropPortrait: "Portrait",
    editorCropLandscape: "Landscape",
    editorLayerLocked: "Layer Locked",
    editorDeleteLayer: "Delete",
    editorNoLayers: "No layers",
    editorDeleteObject: "Delete Selected Object",
    filterNone: "None",
    filterGrayscale: "B&W",
    filterSepia: "Sepia",
    filterInvert: "Invert",
    filterWarm: "Warm",
    filterCool: "Cool",
    filterVintage: "Vintage",
    // AI Tools
    aiToolAddObject: "Add Object",
    aiToolEnhance: "Enhance",
    aiToolRemoveBg: "Remove BG",
    aiTitleGenerate: "Generate Object",
    aiLabelSticker: "Add Sticker (Transparent BG)",
    aiBtnGenerate: "Generate",
    aiTitleEnhance: "Smart Enhance",
    aiDescEnhance: "Automatically adjust brightness, contrast, and saturation for the perfect look.",
    aiBtnEnhance: "Apply Magic Fix",
    aiTitleRemoveBg: "Remove Background",
    aiDescRemoveBg: "Remove the background from your image instantly.",
    aiBtnRemoveBg: "Remove Background",
    aiPromptPlaceholder: "e.g. A red sunglasses",
    aiSizeScale: "Object Size",
    aiSuccessEnhance: "AI Enhancement applied!",
    aiComingSoonBg: "Background removal is coming soon!",
    aiRemoving: "Removing background with AI...",
    
    // AI Brush / Improve
    aiImproveTitle: "Improve Image",
    aiImproveDesc: "Paint over the area you want to improve.",
    aiBrushSize: "Brush Size",
    aiStrength: "AI Strength",
    aiClear: "Clear",
    aiApply: "Apply",
    aiImproving: "Improving...",
    aiImproveSuccess: "Area improved successfully!",
    aiImproveFail: "Failed to improve area.",
    aiImproveNoMask: "Please paint over an area to improve.",

    // Unit Converter
    ucLength: "Length",
    ucArea: "Area",
    ucVolume: "Volume",
    ucMass: "Mass",
    ucTemperature: "Temperature",
    ucTime: "Time",
    ucDigital: "Digital",
    ucInputLabel: "Input Value",
    ucResultLabel: "Result",
    ucSelectUnit: "Select Unit",
    // Units
    unit_mm: "mm",
    unit_cm: "cm",
    unit_m: "m",
    unit_km: "km",
    unit_inch: "inch",
    unit_foot: "foot",
    unit_yard: "yard",
    unit_mile: "mile",
    unit_cm2: "cm²",
    unit_m2: "m²",
    unit_hectare: "hectare",
    unit_acre: "acre",
    unit_milliliters: "milliliters",
    unit_liters: "liters",
    unit_drops: "drops",
    unit_teaspoons: "teaspoons",
    unit_tablespoons: "tablespoons",
    unit_cups: "cups",
    unit_fluid_ounces: "fluid ounces",
    unit_gallons: "gallons",
    unit_mg: "mg",
    unit_g: "g",
    unit_kg: "kg",
    unit_ton: "ton",
    unit_ounce: "ounce",
    unit_pound: "pound",
    unit_Celsius: "Celsius",
    unit_Fahrenheit: "Fahrenheit",
    unit_Kelvin: "Kelvin",
    unit_seconds: "seconds",
    unit_minutes: "minutes",
    unit_hours: "hours",
    unit_days: "days",
    unit_bytes: "bytes",
    unit_KB: "KB",
    unit_MB: "MB",
    unit_GB: "GB",
    unit_TB: "TB",

    // Color Analyzer
    caTabCamera: "Camera",
    caTabImage: "Image",
    caStartCamera: "Start Camera",
    caStopCamera: "Stop Camera",
    caCaptureColor: "Freeze Color",
    caPickImage: "Upload Image",
    caDragDrop: "or drag and drop an image here",
    caColorName: "Color Name",
    caCopied: "Copied!",
    caCopyFail: "Failed to copy",
    caInstruction: "Tap anywhere on the image to pick a color",

    // Currency Converter
    ccFrom: "From",
    ccTo: "To",
    ccAmount: "Amount",
    ccResult: "Converted Amount",
    ccUpdate: "Update Rates",
    ccLastUpdate: "Last Update:",
  },
  pt: {
    appTitle: "Artify",
    createArt: "Criar nova arte",
    desc: "Transforme seus textos em obras de arte únicas usando",
    promptPlaceholder: "Descreva sua imaginação... (ex: Uma cidade cyberpunk futurista à noite com luzes neon)",
    styleLabel: "Estilo Artístico",
    ratioLabel: "Proporção",
    generate: "Gerar Arte",
    generating: "Criando Obra-prima...",
    generatingShort: "Criando...",
    changeImage: "Alterar Imagem",
    addReference: "Adicionar Referência",
    download: "Baixar",
    share: "Compartilhar",
    readyToCreate: "Pronto para Criar",
    readyDesc: "Selecione um estilo, digite um prompt e veja o Artify dar vida às suas ideias.",
    loadingDesc: "Analisando seus pixels...",
    insufficientTokens: "Tokens insuficientes. Faça upgrade para o Plus ou aguarde a recarga.",
    tokens: "Tokens",
    basicPlan: "Básico",
    plusPlan: "Plus",
    generatedWith: "Gerado com Artify",
    currentPlan: "Plano Atual",
    resolution: "Resolução",
    model: "Modelo",
    unlimited: "Ilimitado",
    day: "dia",
    back: "Voltar",
    editImage: "Editar Imagem",
    // Selection Screen
    photoEditor: "Editor de Fotos",
    photoEditorDesc: "Edite e melhore suas fotos como um profissional.",
    aiGenerator: "Gerar Imagens com IA",
    aiGeneratorDesc: "Transforme texto em imagens incríveis.",
    tools: "Ferramentas",
    toolsDesc: "Utilitários úteis para criadores e designers.",
    unitConverter: "Conversor de Unidades",
    unitConverterDesc: "Converta unidades universais instantaneamente.",
    colorAnalyzer: "Analisador de Cores",
    colorAnalyzerDesc: "Analise cores da câmera ou imagens.",
    currencyConverter: "Conversor de Moedas",
    currencyConverterDesc: "Taxas de câmbio em tempo real.",
    comingSoon: "Em Breve!",
    editorComingSoon: "O editor de fotos está em desenvolvimento.",
    // Mode Selection
    selectModeTitle: "Escolha o Modo",
    selectModeDesc: "Selecione como você deseja criar sua obra-prima",
    modeManual: "Editor Manual",
    modeManualDesc: "Ferramentas profissionais clássicas. Ajuste, recorte, filtre e desenhe com controle preciso.",
    modeAI: "Editar com IA",
    modeAIDesc: "Melhore imagens, remova fundos e adicione objetos gerados por IA instantaneamente.",
    aiModeBadge: "MODO IA",
    // Styles
    [ArtStyle.NONE]: "Sem Estilo",
    [ArtStyle.ANIME]: "Anime",
    [ArtStyle.CARICATURE]: "Caricatura",
    [ArtStyle.REALISTIC]: "Realista",
    [ArtStyle.CARTOON]: "Cartoon",
    // Ratios
    [AspectRatio.SQUARE]: "Quadrado (1:1)",
    [AspectRatio.PORTRAIT]: "Retrato (3:4)",
    [AspectRatio.LANDSCAPE]: "Paisagem (4:3)",
    [AspectRatio.WIDE]: "Wide (16:9)",
    [AspectRatio.TALL]: "Stories (9:16)",
    // Editor
    editorUpload: "Carregar Foto",
    editorDragDrop: "ou arraste e solte",
    editorTools: "Ferramentas",
    editorAdjust: "Ajustar",
    editorFilters: "Filtros",
    editorCrop: "Recortar",
    editorDraw: "Desenhar",
    editorText: "Texto",
    editorSticker: "Adesivos",
    editorLayers: "Camadas",
    editorImport: "Add Imagem",
    editorSave: "Salvar",
    editorCancel: "Cancelar",
    editorUndo: "Desfazer",
    editorRedo: "Refazer",
    editorBrightness: "Brilho",
    editorContrast: "Contraste",
    editorSaturation: "Saturação",
    editorBlur: "Desfoque",
    editorHue: "Matiz",
    editorRotate: "Girar",
    editorFlipH: "Espelhar H",
    editorFlipV: "Espelhar V",
    editorBrushSize: "Tamanho",
    editorColor: "Cor",
    editorAddText: "Add Texto",
    editorTextPlaceholder: "Digite o texto...",
    editorCropOriginal: "Original",
    editorCropSquare: "Quadrado",
    editorCropPortrait: "Retrato",
    editorCropLandscape: "Paisagem",
    editorLayerLocked: "Fundo Bloqueado",
    editorDeleteLayer: "Excluir",
    editorNoLayers: "Sem camadas",
    editorDeleteObject: "Excluir Objeto",
    filterNone: "Normal",
    filterGrayscale: "P&B",
    filterSepia: "Sépia",
    filterInvert: "Inverter",
    filterWarm: "Quente",
    filterCool: "Frio",
    filterVintage: "Vintage",
    // AI Tools
    aiToolAddObject: "Add Objeto",
    aiToolEnhance: "Melhorar",
    aiToolRemoveBg: "Remover Fundo",
    aiTitleGenerate: "Gerar Objeto",
    aiLabelSticker: "Add Adesivo (Fundo Transparente)",
    aiBtnGenerate: "Gerar",
    aiTitleEnhance: "Melhoria Inteligente",
    aiDescEnhance: "Ajuste automaticamente brilho, contraste e saturação.",
    aiBtnEnhance: "Aplicar Correção",
    aiTitleRemoveBg: "Remover Fundo",
    aiDescRemoveBg: "Remova o fundo da sua imagem instantaneamente.",
    aiBtnRemoveBg: "Remover Fundo",
    aiPromptPlaceholder: "ex: Um óculos vermelho",
    aiSizeScale: "Tamanho do Objeto",
    aiSuccessEnhance: "Melhoria de IA aplicada!",
    aiComingSoonBg: "Remoção de fundo em breve!",
    aiRemoving: "Removendo fundo com IA...",

    // AI Brush / Improve
    aiImproveTitle: "Melhorar Imagem",
    aiImproveDesc: "Pinte sobre a área que deseja melhorar.",
    aiBrushSize: "Tamanho do Pincel",
    aiStrength: "Força da IA",
    aiClear: "Limpar",
    aiApply: "Aplicar",
    aiImproving: "Melhorando...",
    aiImproveSuccess: "Área melhorada com sucesso!",
    aiImproveFail: "Falha ao melhorar a área.",
    aiImproveNoMask: "Por favor, pinte sobre uma área para melhorar.",

    // Unit Converter
    ucLength: "Comprimento",
    ucArea: "Área",
    ucVolume: "Volume",
    ucMass: "Massa",
    ucTemperature: "Temperatura",
    ucTime: "Tempo",
    ucDigital: "Digital",
    ucInputLabel: "Valor de Entrada",
    ucResultLabel: "Resultado",
    ucSelectUnit: "Selecione a Unidade",
    // Units
    unit_mm: "mm",
    unit_cm: "cm",
    unit_m: "m",
    unit_km: "km",
    unit_inch: "polegada",
    unit_foot: "pé",
    unit_yard: "jarda",
    unit_mile: "milha",
    unit_cm2: "cm²",
    unit_m2: "m²",
    unit_hectare: "hectare",
    unit_acre: "acre",
    unit_milliliters: "mililitros",
    unit_liters: "litros",
    unit_drops: "gotas",
    unit_teaspoons: "colheres de chá",
    unit_tablespoons: "colheres de sopa",
    unit_cups: "xícaras",
    unit_fluid_ounces: "onças fluidas",
    unit_gallons: "galões",
    unit_mg: "mg",
    unit_g: "g",
    unit_kg: "kg",
    unit_ton: "tonelada",
    unit_ounce: "onça",
    unit_pound: "libra",
    unit_Celsius: "Celsius",
    unit_Fahrenheit: "Fahrenheit",
    unit_Kelvin: "Kelvin",
    unit_seconds: "segundos",
    unit_minutes: "minutos",
    unit_hours: "horas",
    unit_days: "dias",
    unit_bytes: "bytes",
    unit_KB: "KB",
    unit_MB: "MB",
    unit_GB: "GB",
    unit_TB: "TB",

    // Color Analyzer
    caTabCamera: "Câmera",
    caTabImage: "Imagem",
    caStartCamera: "Iniciar Câmera",
    caStopCamera: "Parar Câmera",
    caCaptureColor: "Congelar Cor",
    caPickImage: "Carregar Imagem",
    caDragDrop: "ou arraste e solte uma imagem aqui",
    caColorName: "Nome da Cor",
    caCopied: "Copiado!",
    caCopyFail: "Falha ao copiar",
    caInstruction: "Toque em qualquer lugar da imagem para escolher uma cor",

    // Currency Converter
    ccFrom: "De",
    ccTo: "Para",
    ccAmount: "Valor",
    ccResult: "Valor Convertido",
    ccUpdate: "Atualizar Taxas",
    ccLastUpdate: "Última atualização:",
  }
};